apiVersion: v1
kind: Service
metadata:
  name: pulseops-api
  namespace: pulseops
spec:
  type: NodePort
  selector:
    app: pulseops-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulseops-api
  namespace: pulseops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pulseops-api
  template:
    metadata:
      labels:
        app: pulseops-api
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:16-alpine
          command:
            - sh
            - -c
            - until pg_isready -h postgres -U pulseops; do sleep 2; done
      containers:
        - name: api
          image: pulseops:manual
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: pulseops-secrets
                  key: DATABASE_URL
            - name: ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: pulseops-config
                  key: ALLOWED_HOSTS
          resources:
            requests:
              cpu: 50m
              memory: 96Mi
            limits:
              cpu: 300m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
